### ISSUE TITLE
Sign up with Google

### ISSUE THREAD

**Issue by softwarebyze** [softwarebyze/Places#134]
This [will break Expo Go](https://docs.expo.dev/guides/google-authentication/#prerequisites).

Reference: https://docs.expo.dev/guides/google-authentication/#configure-google-project-for-android-and-ios

- [x] install library with ```npx expo install @react-native-google-signin/google-signin```
- [x] add config plugin
```
{
  "expo": {
    "android": {
      "googleServicesFile": "./google-services.json"
    },
    "ios": {
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "plugins": ["@react-native-google-signin/google-signin"]
  }
}
```

- [x] Rebuild app
- [x] Configure
```
import { GoogleSignin } from '@react-native-google-signin/google-signin';

GoogleSignin.configure();
```

- [x] Set up Firebase [iOS](https://docs.expo.dev/guides/google-authentication/#ios)
- [ ] Set up Firebase [Android](https://docs.expo.dev/guides/google-authentication/#android)
- [ ] [Upload google-services.json and GoogleService-Info.plist to EAS](https://docs.expo.dev/guides/google-authentication/#upload-google-servicesjson-and-googleservice-infoplist-to-eas)
- [ ] [Sign in](https://github.com/react-native-google-signin/google-signin#signinoptions--loginhint-string-)

**Comment by softwarebyze** [comment]
![simulator_screenshot_A4998D70-3F93-4134-9850-5557A681C166](https://github.com/softwarebyze/Places/assets/77241170/585ef9bf-42d4-4148-96b2-b054011a1e9e)

**Comment by softwarebyze** [comment]
I think I need to [dig into xcode](https://github.com/react-native-google-signin/google-signin/blob/master/docs/ios-guide.md) in order to get past this

**Comment by YonahFeld** [comment]
Added plus for September 14th
