### ISSUE TITLE
Attach Photo Formating

### ISSUE THREAD

**Issue by YonahFeld** [softwarebyze/Places#195]
**Describe the bug**
When you click to attach a photo, your photo reel appears in a weird way

**To Reproduce**

1. Go to a chat 
2. attach a photo to your message
3. too much space between the pictures and the buttons

**Expected behavior**
Properly formatted UI

**Screenshots**
![img_3465_720](https://github.com/softwarebyze/Places/assets/87882768/533b6fee-d7ac-4ae8-acd1-0e3c6c7f7857)

**Smartphone (please complete the following information):**

- Device: iPhone 12
- Version: Latest build

**Additional context**

**Comment by softwarebyze** [comment]
Fixed by adding an OverlayProvider
<img width="1310" alt="image" src="https://github.com/softwarebyze/Places/assets/77241170/34bf3811-62a9-4851-9838-9f24ac87b23c">
