### ISSUE TITLE
Backend/Join a Place

### ISSUE THREAD

**Issue by softwarebyze** [softwarebyze/Places#9]
- [x] #90
- [x] Query to get categories of places - OK to leave hardcoded for now
- [x] Query to get places (name, city, image, number of members) based on category and city
- [x] Query for user to save a city
- [x] Query for user to save interests
- [x] Query to get all interests (including which category)
- [x] Query to join a place

**Comment by YonahFeld** [comment]
All backend related work to joining a place - September 14th Label
