### ISSUE TITLE
No connection popup

### ISSUE THREAD

**Issue by softwarebyze** [softwarebyze/Places#94]
If there's no internet connection during signup or login, show [this popup](https://www.figma.com/file/0D5awSceV5ZH9sWMe3S5Hq/Final-Places-File?type=design&node-id=477-4924&mode=design&t=kUX1UX0PMNxHCrvI-4). You can follow [this example](https://reactnative.dev/docs/modal#example)

**Comment by simonac2-gif** [comment]
need help to make tostring and fetch work
